version: '3.8'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: projectk-zookeeper
    ports:
      - "2181:2181"
    networks:
      - projectk

  kafka:
    image: wurstmeister/kafka:latest
    container_name: projectk-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "StartProcess:1:1,FinishProcess:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - ./docker-local-data/var/run/docker.sock:/var/run/docker.sock
      - ./docker-local-data/kafka/data:/var/lib/kafka/data
    networks:
      - projectk

  postgresql:
    image: postgres:14.1-alpine
    container_name: projectk-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    volumes:
      - ./docker-local-data/postgresql/data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - projectk

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8484:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      DB_VENDOR: postgres
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak_admin
      DB_PASSWORD: changeme
    command:
      - start-dev
    depends_on:
      - postgresql
    networks:
      - projectk

networks:
  projectk:
    driver: bridge